apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: Jenkins
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: harinath926/python
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

